version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  BeforeInstall:
    - location: scripts/codedeploy-cleanup.sh
      timeout: 300
      runas: root
    - location: scripts/remove-old-app.sh
      timeout: 300
      runas: root
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/docker-cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
    # 
  # ApplicationStart:
  #   - location: scripts/application-start.sh
  #     timeout: 300
  #     runas: root
  # ValidateService:
  #   - location: scripts/validate-service.sh
  #     timeout: 300
  #     runas: root