version: '3.8'

services:
  app:
    build:
      context: .
    image: solelreactmap:latest 
    container_name: solelreactmap
    ports:
      - '3000:3000'
    networks:
      - app-network
    env_file:
      - .env.local
    restart: always # Ensures the container restarts if it crashes
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/ssl:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge